### ISSUE TITLE
Questiong on cronjob

### ISSUE THREAD

**Issue by killmasta93** [ScholarshipOwl/mautic-docker-compose#2]
HI
I was wondering how i can enable to run the cron jobs every min or something faster? as it takes around 1 hour to send the emails?

Thanks

**Comment by R3VoLuT1OneR** [comment]
@killmasta93 
You should look into the cron tab `/etc/cron.d/mautic` to change cron commands timings.

Code from official docker image, and how does it works now.
https://github.com/mautic/docker-mautic/blob/mautic4/common/mautic.crontab
https://github.com/mautic/docker-mautic/blob/mautic4/apache/Dockerfile

But overall it depends on type of the email you are trying to send, number of users in DB etc.
If it's segment email, so user first need to be added to the segment by `mautic:segments:update` job and then to be catched by `mautic:broadcasts:send` command to generate and email if it's queue and not immediate (look into the email configuration) only then it will be sent by `mautic:emails:send` command.

So there are multiple factors affecting the email sending speed depend on your need everything can be improved.

By the way purpose of this repository is not to be used on production, but an example and for local environment tests.

**Comment by killmasta93** [comment]
thanks for the reply,  
currently we tried running this command in the cron job

`/var/www/html/bin/console mautic:campaigns:trigger`

i assume this triggers the send also?
